# Konfiguracja backendu - mówimy CMS-owi, jak ma się łączyć z GitHubem
backend:
  name: git-gateway # Używamy bramy Git od Netlify
  branch: main # Nazwa Twojej głównej gałęzi (może być też 'master')

# Definicja kolekcji - czyli typów treści, które można edytować.
# Możesz tu dodać np. "Strony", "Projekty" itp.
collections:
  - name: "wydarzenia" # Nazwa techniczna kolekcji
    label: "Wydarzenia" # Nazwa wyświetlana w panelu
    folder: "content/blog" # Folder, w którym są pliki z wpisami
    create: true # Pozwól na tworzenie nowych wpisów
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Szablon nazwy dla nowych plików
    media_folder: "static/images/{{slug}}" # Ścieżka zapisu obrazków
    public_folder: "/images/{{slug}}" # Jak odnosić się do obrazków w treści wpisu
    fields: # Pola do wypełnienia dla każdego wpisu
      - { label: "Tytuł", name: "title", widget: "string" }
      - { label: "Data publikacji", name: "date", widget: "datetime" }
      - { label: "Kategoria", name: "categories", widget: "select", options: ["Wydarzenie", "Ogłoszenie"] }
      - { label: "Wersja robocza (Draft)", name: "draft", widget: "boolean", default: true }
      - { label: "Treść", name: "body", widget: "markdown" }